<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-Website-f8749803-1d03-48e6-b415-f79521e8a8b0</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.20" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.20" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.20" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.20" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.20" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.20" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.7" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\Admin\Controllers\" />
    <Folder Include="Areas\Admin\Data\" />
    <Folder Include="Areas\Admin\Models\" />
    <Folder Include="Areas\Admin\Views\" />
    <Folder Include="Areas\User\Data\" />
    <Folder Include="Areas\User\Models\" />
    <Folder Include="Controllers\" />
    <Folder Include="wwwroot\CSS\Admin\Components\" />
    <Folder Include="wwwroot\CSS\Admin\Views\" />
    <Folder Include="wwwroot\CSS\User\Components\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\Images\Logos\ArcadiaLogo.png" />
    <None Include="wwwroot\Images\Logos\ArcadiaLogoSmall.png" />
  </ItemGroup>

</Project>
